// <auto-generated />
namespace PrjCinema.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class A2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A2));
        
        string IMigrationMetadata.Id
        {
            get { return "201707071408201_A2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
